###
GET {{url}}person
Authorization: Bearer {{token}}

###
GET {{url}}person/1
Authorization: Bearer {{token}}

###
DELETE {{url}}person/6
Authorization: Bearer {{token}}

###
POST {{url}}person
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Karl",
  "lastName": "Hansen",
  "age": "55",
  "email": "karl@mail.com",
  "address": {
    "street": "Lyngby Hovedgade",
    "number": "55"
  },
  "zipCode": "2800",
  "phoneNumbers": [
    {
      "number": "12345678",
      "description": "Home"
    },
    {
      "number": "87654321",
      "description": "Work"
    }
  ],
  "hobbies": ["Soccer", "Tennis", "Golf"]
}

###
PUT {{url}}person/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Karl",
  "lastName": "HansenData",
  "age": "55",
  "email": "karl@mail.com"
}